print("escriba su primer nombre")
a = input()
print("escriba su segundo nombre")
b = input()
print("escriba su primer apellido")
c = input()
print("escriba su segundo apellido")
d = input()
print("que eadad tienes")
e = input()
print("cual es su fecha de nacimiento")
f = input()